### ISSUE TITLE
Simplify filterOrder header in UG

### ISSUE THREAD

**Issue by kaixuan477** [AY2425S1-CS2103T-F14a-2/tp#143]
![image](https://github.com/user-attachments/assets/f297c2c3-b6e9-4494-b73f-421061bc046f)
Present header for the `filterOrder` command is lengthy and not very intuitive.

**Comment by awdse22** [comment]
![image](https://github.com/user-attachments/assets/bce5691c-a5fc-4aeb-88fd-c1020f0c81d3)
Already done.
