### ISSUE TITLE
[PE-D][Tester B] Unsanitized Phone Number

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F14a-2/tp#273]
![image.png](https://raw.githubusercontent.com/WeiHanWong/ped/main/files/f27719b9-54c0-4ef6-aaf5-dd49b1b2a352.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: WeiHanWong/ped#1

**Comment by awdse22** [comment]
Long phone number is considered malicious input by CS2103T
