### ISSUE TITLE
[PE-D][Tester C] Customers with identical phone number

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F14a-2/tp#275]
![image.png](https://raw.githubusercontent.com/keithxun/ped/main/files/a6483124-3544-4ba0-a917-dcf9e6fd3267.png)

- 2 Customers with the same phone number
- Expected: Reject as 2 people should not have the same phone number
- Actual: Accepted

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: keithxun/ped#7

**Comment by awdse22** [comment]
Customers may have the same phone number e.g. What if a parent's sons/daughters use their parent's phone number?
