### ISSUE TITLE
[PE-D][Tester C] Small grammar mistakes in DG

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14a-2/tp#284]
![image.png](https://raw.githubusercontent.com/keithxun/ped/main/files/a5e491cf-7f7c-430d-9139-41f2b7713be4.png)

Grammar

Should be optimum instead of optimal

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: keithxun/ped#9

**Comment by FooChao** [comment]
is the other way
