### ISSUE TITLE
[PE-D][Tester C] Email validation for .domainName

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F14a-2/tp#290]
![image.png](https://raw.githubusercontent.com/keithxun/ped/main/files/91c5b8ff-7d96-4219-8829-26276678229e.png)

- Email validation may want to include .com, .sg or .domainName

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: keithxun/ped#13

**Comment by awdse22** [comment]
Not all emails have domain name

**Comment by FooChao** [comment]
Maybe can put in future enhancements to give warning?
