### ISSUE TITLE
Allow commands to be case-insensitive

### ISSUE THREAD

**Issue by kaixuan477** [AY2425S1-CS2103T-F14a-2/tp#75]

**Comment by awdse22** [comment]
Switch statements only allow comparison with constants, not expressions. Hence, toLowerCase() or toUpperCase() cannot be used unless we're willing to change the whole thing to a bunch of if/else if statements
![image](https://github.com/user-attachments/assets/48717cbd-d8b6-4910-86fc-d413a9ecadd4)

**Comment by FooChao** [comment]
can't we to lower case the commandword? and then change the COMMAND_WORD to lower case?
